export default {
    ADD_PRODUCT: 'ADD_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',

    SET_INPUT_ID: 'SET_INPUT_ID',
    SET_INPUT_NAME: 'SET_INPUT_NAME',
    SET_INPUT_CATEGORY: 'SET_INPUT_CATEGORY',
    SET_INPUT_MEASURE: 'SET_INPUT_MEASURE',
    SET_INPUT_BRAND: 'SET_INPUT_BRAND',
    SET_INPUT_AMOUNT: 'SET_INPUT_AMOUNT',
    SET_INPUT_PRICE: 'SET_INPUT_PRICE',
    SET_INPUT_CHARACTERISTIC: 'SET_INPUT_CHARACTERISTIC',
    SET_INPUT_DATE: 'SET_INPUT_DATE',

    RESET_INPUT: 'RESET_INPUT'
}